baseURL = "https://krlmlr.github.io/slides/"
languageCode = "en-us"
title = "Slide decks by Kirill Müller"

theme = "hugo-theme-one"
#googleAnalytics = "UA-123-45"

[params]
    navigation = ["archives.md", "about.md"]

publishDir = "docs"
