baseURL = "https://example.com"
languageCode = "en-us"
title = "Hugo Theme One"

theme = "hugo-theme-one"
googleAnalytics = "UA-123-45"

[params]
    navigation = ["archives.md", "about.md"]

publishDir = "docs"
